### ISSUE TITLE
issueベースの開発_レビュー用

### ISSUE THREAD

**Issue by kurako100** [kurako100/GiBook#9]

**Comment by Tsuchiya2** [comment]
![image](https://github.com/user-attachments/assets/52638dce-6121-4388-adb3-c387f32393a4)

対応ありがとうございます。
Projectsページにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認いただいて、レビューワー側で上記が確認できるように対応いただき、再提出操作をお願いいたします。

**Comment by kurako100** [comment]
失礼いたしました...
publicに変更しましたので、再度ご確認お願いいたします。

**Comment by tmtkzk0823** [comment]
ご対応ありがとうございます。
概ね良さそうです！
LGTMです！

**Comment by kurako100** [comment]
ご確認いただきありがとうございます！
